### ISSUE TITLE
[Bug] - Usage shows old system usage

### ISSUE THREAD

**Issue by IzMichael** [theta-tools/Theta-Tools#14]
**Category**
[ ] Text Based (Typo, etc.)
[x] Missing or Inaccurate Info
[ ] Incorrect / Broken Link
[ ] Other

**Describe the bug**
The 'Usage' page in the Documentation still shows how to use the old system.

**Expected behavior**
The 'Usage' page in the Documentation should explain the code system and the implement button.

**Screenshots**
![image](https://user-images.githubusercontent.com/57115702/95036653-16a49000-0725-11eb-83da-0a772c839b3e.png)

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Edge Dev - Chromium
Version: 87.0.654.0 (Official build) dev (64-bit)

**Additional context**
N/A

**Comment by 16sweetyjain** [comment]
@IzMichael i didnt get this. how are you planning to implement it? The "Components" is not a link here.

**Comment by IzMichael** [comment]
@16sweetyjain this issue is just me tracking a change
