### ISSUE TITLE
[Bug] - Component Documentation is missing 'Implement' button

### ISSUE THREAD

**Issue by IzMichael** [theta-tools/Theta-Tools#15]
**Category**
[ ] Text Based (Typo, etc.)
[ ] Missing or Inaccurate Info
[ ] Incorrect / Broken Link
[x] Other

**Describe the bug**
Component Documentation is missing 'Implement' button.

**Expected behavior**
There should be a button in the documentation for each component that copies the code to the user's clipboard.

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Edge Dev - Chromium
Version: 87.0.654.0 (Official build) dev (64-bit)

**Additional context**
N/A

**Comment by 16sweetyjain** [comment]
@IzMichael would you please give me more insight to the bug?

**Comment by IzMichael** [comment]
@16sweetyjain used the wrong template, just realised :) I'll open a new issue
