### ISSUE TITLE
[Feature] - New Front Page

### ISSUE THREAD

**Issue by IzMichael** [theta-tools/Theta-Tools#18]
**Describe the solution you'd like**
The current front page is just a temporary design, so if anyone wants to re-design it, go right ahead!

**Additional context**
Keep the header the same.

**Comment by KushalBhanot** [comment]
Hey! I can try this.

**Comment by IzMichael** [comment]
> Hey! I can try this.

Great! Let me know if you need assistance 😀

**Comment by IzMichael** [comment]
@KushalBhanot Great! Let me know if you need assistance.

**Comment by IzMichael** [comment]
@KushalBhanot, How are you going with this?

**Comment by IzMichael** [comment]
Resolved in Re-Design https://github.com/theta-tools/main-repository
