### ISSUE TITLE
[Bug] - Links still point to old URL

### ISSUE THREAD

**Issue by IzMichael** [theta-tools/Theta-Tools#19]
**Category**
[ ] Text Based (Typo, etc.)
[ ] Missing or Inaccurate Info
[x] Incorrect / Broken Link
[ ] Other

**Describe the bug**
Some links in the `.md` files still link to pages at `https://theta-tools.github.io`.

**Expected behavior**
Those links should be pages at `https://thetatools.xyz`.

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Edge Dev - Chromium
Version: 87.0.654.0 (Official build) dev (64-bit)

**Additional context**
N/A

**Comment by rperry99** [comment]
I can fix the links for you if you want.

**Comment by IzMichael** [comment]
@rperry99 Great! Let me know if you need assistance.

**Comment by IzMichael** [comment]
@all-contributors please add @rperry99 for Bug reports

**Comment by IzMichael** [comment]
@all-contributors please add @rperry99 for Bug reports
