### ISSUE TITLE
[Feature] - LOGIN PAGE

### ISSUE THREAD

**Issue by deVedant** [theta-tools/Theta-Tools#23]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Just a clean Login page having several essential entities.

**Describe alternatives you've considered**
N/A

**Additional context**
One can even integrate this with the backend and then it's good to go!

**Comment by deVedant** [comment]
Can I claim?

**Comment by IzMichael** [comment]
@deVedant Go for it! Remember to read the contributing guidelines at https://thetatools.xyz/contributing/
